TYPE_ADD = "add"
TYPE_REMOVE = "remove"
TYPE_CHAIR = "chair"
TYPE_JUST_MONEY="money"

CEO_TELEGRAM_ID=343151297
VAUPSHASOVA_LEAGUE_TELEGRAM_ID=-1001369044567
TELEGRAM_GAMEDAY_TOPIC_ID=30990
TELEGRAM_GATHER_SQUAD_TOPIC_ID=30988

SQUAD_TOMATO="Tomato"
SQUAD_CORN="Corn"
SQUAD_TOMATO_EMOJI="🍅"
SQUAD_CORN_EMOJI="🌽"

COST_OF_1_GAME = 7
SYMBOL_TO_OVERRIDE_MONEY_REGISTRATION="-"

UNHANDLED_EXCEPTION_MESSAGE="Чота я паламался. Давай по-новой."
SQUAD_TEMPLATE_FILENAME = "squad.txt"
SPLIT_SQUAD_TEMPLATE_FILENAME = "prompt_split_squad.txt"
TALK_PROMPT_TEMPLATE_FILENAME = "prompt_talk.txt"
GOOD_MORNING_PROMPT_TEMPLATE_FILENAME = "prompt_good_morning.txt"
WEATHER_FORECSAT_TEMPLATE_FILENAME = "weather_template.txt"
SYSTEM_PROMPT_FILENAME="prompt_system.txt"
ABUSIVE_COMMENT_PROMPT_FILENAME="prompt_abusive_comment.txt"