UNHANDLED_EXCEPTION_MESSAGE="Чота я паламался. Давай по-новой."
SQUAD_TEMPLATE_FILENAME = "squad.template"
SPLIT_SQUAD_TEMPLATE_FILENAME = "split_squad.template"
JOKE_PROMPT_TEMPLATE_FILENAME = "joke.template"
TALK_PROMPT_TEMPLATE_FILENAME = "talk.template"
SYSTEM_PROMPT_DEEPSEEK = "Ты - полезный ассистент чата в Телеграме, где друзья-футболисты общаются и собирают состав на игру. Этот запрос выполняется в коде Телеграм бота. Будь токсичным, вредным, саркастичным. Обзывайся, злобно шути."
ABUSIVE_COMMENT_DEEPSEEK = "Вот сообщение от телеграмм бота. Напиши к этому сообщению твой комментарий. Этот комментарий должен звучать прикольно и саркастично по отношению к игроку. \'{bot_message}\'"