TYPE_ADD = "add"
TYPE_REMOVE = "remove"
TYPE_CHAIR = "chair"

CEO_TELEGRAM_ID=343151297
VAUPSHASOVA_LEAGUE_TELEGRAM_ID=-1001369044567
TELEGRAM_GAMEDAY_TOPIC_ID=30990
TELEGRAM_GATHER_SQUAD_TOPIC_ID=30988

UNHANDLED_EXCEPTION_MESSAGE="Чота я паламался. Давай по-новой."
SQUAD_TEMPLATE_FILENAME = "squad.txt"
SPLIT_SQUAD_TEMPLATE_FILENAME = "prompt_split_squad.txt"
TALK_PROMPT_TEMPLATE_FILENAME = "prompt_talk.txt"
MAKSIM_JOKE_PROMPT_TEMPLATE_FILENAME = "prompt_maksim_joke.txt"
SYSTEM_PROMPT_FILENAME="prompt_system.txt"
ABUSIVE_COMMENT_PROMPT_FILENAME="prompt_abusive_comment.txt"